server:
  port: 11000


#设置服务名称 和 环境配置
spring:
  application:
    name: service-one
  profiles:
    #@active.dev@
    active: dev

eureka:
  instance:
    #是否优先使用服务实例的IP地址，相较于hostname	默认：false
    prefer-ip-address: true
    #实例id
    instance-id: customer-instance-one
  client:
    service-url:
      defaultZone : http://eureka12000.com:12000/eureka/,http://eureka12001.com:12001/eureka/


info:
  app.name : eureka-client-11000

#feign配合熔断器hystrix使用
feign:
  httpclient:
    connection-timeout: 30000
  hystrix:
    enabled: true

#设置hystrix相关配置
hystrix:
  command :
    default :
      execution :
        isolation :
          thread :
            # 设置熔断超时时间
            timeoutInMilliseconds: 3000
        timeout :
          # 开启熔断功能
          enabled : true


