server:
  port: 11000


#设置服务名称 和 环境配置
spring:
  application:
    name: service-one
  profiles:
    #@active.dev@
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybase?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 20
  redis:
    host: 127.0.0.1
    port: 6379
    #redis有16个数据库，默认0
    database: 0
    timeout: 3000
    
mybatis-plus:
  mapper-locations : classpath:/mapper/*Mapper.xml
  typeAliasesPackage : com.giveu.newwebeurekaclient11000.bean
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #打印sql输出语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eureka:
  instance:
    #是否优先使用服务实例的IP地址，相较于hostname	默认：false
    prefer-ip-address: true
    #实例id
    instance-id: customer-instance-one
  client:
    service-url:
      defaultZone : http://eureka12000.com:12000/eureka/,http://eureka12001.com:12001/eureka/
    # 启用服务消费者从注册中心拉取服务列表的功能
    fetch-registry: true
    # 设置服务消费者从注册中心拉取服务列表的间隔
    registry-fetch-interval-seconds: 30

info:
  app.name : eureka-client-11000

#feign配合熔断器hystrix使用
feign:
  httpclient:
    connection-timeout: 30000
  hystrix:
    enabled: true

#设置hystrix相关配置
hystrix:
  command :
    default :
      execution :
        isolation :
          thread :
            # 设置熔断超时时间
            timeoutInMilliseconds: 3000
        timeout :
          # 开启熔断功能
          enabled : true

#apollo上的配置应用ID
app:
  id: customer-one-config
#apollo脚手架中的meta server url
apollo:
  meta: http://localhost:8080

logging:
  config: classpath:logback-spring.xml
#  level: info

#默认之配置为TM的本机默认端口
#tx-lcn:
#  client:
#    manager-address: 127.0.0.1:7970

# 关闭Ribbon的重试机制（如果有必要）
ribbon:
  MaxAutoRetriesNextServer: 0
  ReadTimeout: 5000
  ConnectTimeout : 5000


#默认之配置为TM的本机默认端口
#tx-lcn:
#  client:
#    manager-address: 127.0.0.1:8070
tx-lcn:
  logger:
    enabled: true
    data-source-jndi-name: ${spring.datasource.driver-class-name}
    jdbc-url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
