server:
  port: 15000

spring:
  application:
    name: zuul-server
eureka:
  instance:
    prefer-ip-address: true
    instance-id: zuul-instance
  client:
    service-url:
      defaultZone : http://eureka12000.com:12000/eureka/,http://eureka12001.com:12001/eureka/

zuul:
  routes:
  #\u5C06\u8DEF\u5F84\u542Bservice1\u7684\u63A5\u53E3\u8DEF\u7531\u7ED9service-one\u670D\u52A1
    service1:
      path: /service1/**
      serviceId : service-one
  #\u5C06\u8DEF\u5F84\u542Bservice3\u7684\u63A5\u53E3\u8DEF\u7531\u7ED9service-third\u670D\u52A1
    service2:
      path: /service3/**
      serviceId : service-third
